import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/models.dart';
import '../providers/app_provider.dart';
import '../services/firestore_service.dart';
import '../widgets/tenant_card.dart';
import 'generate_bill_screen.dart';

class TenantsScreen extends StatelessWidget {
  const TenantsScreen({super.key});

  void _showAddTenantDialog(BuildContext context, FirestoreService firestoreService) {
    final nameController = TextEditingController();
    final rentController = TextEditingController();
    final readingController = TextEditingController();

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Add New Tenant'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              controller: nameController,
              decoration: const InputDecoration(labelText: 'Name'),
              textCapitalization: TextCapitalization.words,
            ),
            TextField(
              controller: rentController,
              decoration: const InputDecoration(labelText: 'Rent Amount (₹)'),
              keyboardType: TextInputType.number,
            ),
            TextField(
              controller: readingController,
              decoration: const InputDecoration(labelText: 'Initial Meter Reading'),
              keyboardType: const TextInputType.numberWithOptions(decimal: true),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () async {
              if (nameController.text.isEmpty) return;
              
              final tenant = Tenant(
                id: '', // Generated by Firestore
                name: nameController.text,
                rent: double.tryParse(rentController.text) ?? 0,
                lastReading: double.tryParse(readingController.text) ?? 0,
                lastReadingDate: Timestamp.now(),
                createdAt: Timestamp.now(),
              );

              await firestoreService.addTenant(tenant);
              if (context.mounted) Navigator.pop(context);
            },
            child: const Text('Add'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final appProvider = Provider.of<AppProvider>(context);
    final firestoreService = FirestoreService(userId: appProvider.user!.uid);

    return Scaffold(
      backgroundColor: Colors.grey[50],
      body: StreamBuilder<List<Tenant>>(
        stream: firestoreService.getTenants(),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Center(child: Text('Error: ${snapshot.error}'));
          }

          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }

          final tenants = snapshot.data ?? [];

          if (tenants.isEmpty) {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.people_outline, size: 64, color: Colors.grey[300]),
                  const SizedBox(height: 16),
                  Text(
                    'No tenants yet',
                    style: TextStyle(color: Colors.grey[500], fontSize: 16),
                  ),
                ],
              ),
            );
          }

          return ListView.builder(
            padding: const EdgeInsets.all(16),
            itemCount: tenants.length,
            itemBuilder: (context, index) {
              final tenant = tenants[index];
              return TenantCard(
                tenant: tenant,
                onTap: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => GenerateBillScreen(tenant: tenant),
                    ),
                  );
                },
                onDelete: () => _showDeleteConfirm(context, firestoreService, tenant.id),
              );
            },
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _showAddTenantDialog(context, firestoreService),
        backgroundColor: Colors.blue[600],
        child: const Icon(Icons.add),
      ),
    );
  }

  void _showDeleteConfirm(BuildContext context, FirestoreService service, String tenantId) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Tenant?'),
        content: const Text('This action cannot be undone.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () {
              service.deleteTenant(tenantId);
              Navigator.pop(context);
            },
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Delete'),
          ),
        ],
      ),
    );
  }
}
